title: "Rosie&#10024;"
color: "#3FBFBF"

socials:
  -
    name: "Bluesky"
    url: "https://bsky.app/profile/did:plc:pq2ioq3xcf7fxaxrrc4bgjwp"
    logo: "bluesky.svg"
    style: "background-color: #1185FE;"
  -
    name: "Instagram"
    url: "https://www.instagram.com/ahillypath/"
    logo: "instagram.svg"
    style: "background-image: linear-gradient(90deg, #FF0069, #D300C5);"
  - 
    name: "Twitch"
    url: "https://twitch.tv/ahillypath"
    logo: "twitch.svg"
    style: "background-color: #9246FF;"
  -
    name: "Twitter"
    url: "https://twitter.com/i/user/3175641238"
    logo: "twitter.svg"
    style: "background-color: #1DA1F2;"
  -
    name: "YouTube"
    url: "https://www.youtube.com/channel/UCROkaAoBA2huDt76FytJFFg"
    logo: "youtube.svg"
    style: "background-color: #FF0033;"