title: "Rosie&#10024;"
color: "#3fbfbf"

links:
  - name: "Bluesky"
    url:  "https://bsky.app/profile/did:plc:pq2ioq3xcf7fxaxrrc4bgjwp"
    icon: "bluesky.svg"
    color: "#1185FE"
  - name: "YouTube"
    url:  "https://youtube.com/channel/UCROkaAoBA2huDt76FytJFFg"
    icon: "youtube.svg"
    color: "#FF0000"
  - name: "Instagram"
    url:  "https://instagram.com/ahillypath"
    icon: "instagram.svg"
    color: "#FF0069"
  - name: "Twitch"
    url:  "https://twitch.tv/ahillypath"
    icon: "twitch.svg"
    color: "#9146FF"